on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #- name: "Check out repository"
       # uses: actions/checkout@v3
      - name: "Build project"
        run: "echo 'Building code...'"
      - name: Build DotNet
        uses: Elskom/build-dotnet@v1.1.1
  verify:
    runs-on: ubuntu-latest
    steps:
      - run: "echo 'Verifying compliance…'"
